In [ ]:
from tensorflow.keras.models import load_model

model = load_model('millets_cnn.h5')

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(
    rescale = 1./255, # Rescale pixel values between 0 and 1
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)


In [ ]:
import numpy as np
from tensorflow.keras.preprocessing import image

# Read the uploaded image
uploaded_image = image.load_img('c.jpg', target_size=(64, 64))

# Preprocess the image
preprocessed_image = image.img_to_array(uploaded_image)
preprocessed_image = datagen.standardize(preprocessed_image)
preprocessed_image = np.expand_dims(preprocessed_image, axis=0)
res = model.predict(preprocessed_image)

result = np.argmax(res)
print(float(res[result][0])*100)
if(float(res[result][0])*100>75):
  print(f"Result is Class {result}")
else:
  print("Model is failed to predict this image")


1/1 [==============================] - 0s 27ms/step
91.04529023170471
Result is Class 0


0.9104529

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing import image

# Read the uploaded image
uploaded_image = image.load_img('d.jpg', target_size=(64, 64))

# Preprocess the image
preprocessed_image = image.img_to_array(uploaded_image)
preprocessed_image = datagen.standardize(preprocessed_image)
preprocessed_image = np.expand_dims(preprocessed_image, axis=0)
model.predict(preprocessed_image)


1/1 [==============================] - 0s 26ms/step


array([[9.9871731e-01, 4.9545059e-05, 1.2331659e-03, 1.9797392e-10]],
      dtype=float32)

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing import image

# Read the uploaded image
for i in range(1,11):
  uploaded_image = image.load_img(f'{i}.jpg', target_size=(64, 64))

# Preprocess the image
  preprocessed_image = image.img_to_array(uploaded_image)
  preprocessed_image = datagen.standardize(preprocessed_image)
  preprocessed_image = np.expand_dims(preprocessed_image, axis=0)
  res = model.predict(preprocessed_image)
  ans={0:"Basmati_1121",1:"Basmati_1509",2:"basmati 1718",3:"Permal"}
  print(res)
  result = np.argmax(res)
  print(result)
  print(float(res[0][result])*100)
  if(float(res[0][result])*100>75):
    print(f"Result is {ans[result]}")
  else:
    print("Model is failed to predict this image")

1/1 [==============================] - 0s 42ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 38ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 36ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 43ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 41ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 44ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 33ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 32ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 29ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509
1/1 [==============================] - 0s 30ms/step
[[0. 1. 0. 0.]]
1
100.0
Result is Basmati_1509


In [ ]:
import numpy as np
from tensorflow.keras.preprocessing import image

# Read the uploaded image
for i in range(1,9):
  uploaded_image = image.load_img(f'{i}.jpg', target_size=(64, 64))

# Preprocess the image
  preprocessed_image = image.img_to_array(uploaded_image)
  preprocessed_image = datagen.standardize(preprocessed_image)
  preprocessed_image = np.expand_dims(preprocessed_image, axis=0)
  res = model.predict(preprocessed_image)
  ans={0:"Basmati_1121",1:"Basmati_1509",2:"basmati 1718",3:"Permal"}
  print(res)
  result = np.argmax(res)
  print(result)
  print(float(res[0][result])*100)
  if(float(res[0][result])*100>75):
    print(f"Result is {ans[result]}")
  else:
    print("Model is failed to predict this image")


1/1 [==============================] - 0s 31ms/step
[[2.8756478e-08 5.3615943e-09 7.6537263e-11 1.0000000e+00]]
3
100.0
Result is Permal
1/1 [==============================] - 0s 31ms/step
[[3.4227961e-14 2.6002771e-11 1.2537350e-16 1.0000000e+00]]
3
100.0
Result is Permal
1/1 [==============================] - 0s 41ms/step
[[6.2008834e-15 1.9643386e-15 5.5263657e-29 1.0000000e+00]]
3
100.0
Result is Permal
1/1 [==============================] - 0s 30ms/step
[[6.2306711e-09 9.8135445e-08 5.2979145e-21 9.9999988e-01]]
3
99.99998807907104
Result is Permal
1/1 [==============================] - 0s 25ms/step
[[3.4726702e-06 7.6628858e-06 5.8097811e-11 9.9998891e-01]]
3
99.99889135360718
Result is Permal
1/1 [==============================] - 0s 25ms/step
[[2.19220198e-11 1.36744045e-11 1.04196060e-21 1.00000000e+00]]
3
100.0
Result is Permal
1/1 [==============================] - 0s 25ms/step
[[3.7255461e-09 1.2847196e-10 1.8034552e-19 1.0000000e+00]]
3
100.0
Result is Permal
1/1 [========

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing import image

# Read the uploaded image
for i in range(10,21):
  uploaded_image = image.load_img(f'{i}.jpg', target_size=(64, 64))

# Preprocess the image
  preprocessed_image = image.img_to_array(uploaded_image)
  preprocessed_image = datagen.standardize(preprocessed_image)
  preprocessed_image = np.expand_dims(preprocessed_image, axis=0)
  res = model.predict(preprocessed_image)
  ans={0:"Basmati_1121",1:"Basmati_1509",2:"basmati 1718",3:"Permal"}
  print(res)
  result = np.argmax(res)
  print(result)
  print(float(res[0][result])*100)
  if(float(res[0][result])*100>75):
    print(f"Result is {ans[result]}")
  else:
    print("Model is failed to predict this image")


1/1 [==============================] - 0s 31ms/step
[[6.3328618e-12 9.6024187e-06 9.9999034e-01 1.0493874e-18]]
2
99.99903440475464
Result is basmati 1718
1/1 [==============================] - 0s 36ms/step
[[5.3367882e-10 9.7015068e-08 9.9999988e-01 8.2982254e-10]]
2
99.99998807907104
Result is basmati 1718
1/1 [==============================] - 0s 27ms/step
[[3.6683434e-09 1.0353760e-05 9.9998963e-01 1.3766127e-17]]
2
99.99896287918091
Result is basmati 1718
1/1 [==============================] - 0s 27ms/step
[[1.4707601e-05 2.5363023e-10 9.9998534e-01 3.8235837e-13]]
2
99.99853372573853
Result is basmati 1718
1/1 [==============================] - 0s 27ms/step
[[1.8934837e-05 1.7151164e-01 8.2846940e-01 7.6736084e-10]]
2
82.84693956375122
Result is basmati 1718
1/1 [==============================] - 0s 25ms/step
[[1.3645128e-05 3.1295934e-07 9.9998605e-01 2.6101124e-16]]
2
99.99860525131226
Result is basmati 1718
1/1 [==============================] - 0s 25ms/step
[[0.0811756  0.010